package First.fargo_soul.dadageneeator.provider;

import First.fargo_soul.mixin.minecraft.LanguageProviderAccessor;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class SoulLangProvider extends LanguageProvider {

    public SoulLangProvider(PackOutput output, String modid, String locale) {
        super(output, modid, locale);
    }

    @Override
    protected void addTranslations() {
        add("fargo_soul.configuration.soul_chance", "Chance for other creatures to carry souls", "其他生物携带魂石的概率");
        add("fargo_soul.configuration.soul_drop_chance", "Chance for soul-carrying creatures to drop souls", "携带魂石的生物掉落魂石的概率");
        add("fargo_soul.configuration.soul_hp_increase_per_soul", "Base HP increase per soul for monsters", "每个魂石提升怪物的基础血量");
        add("fargo_soul.configuration.soul_hp_multiplier_per_soul", "HP multiplier per soul for monsters", "每个魂石提升怪物的血量系数");
        add("fargo_soul.configuration.soul_size_multiplier_per_soul", "Size multiplier per soul for monsters", "每个魂石提升怪物的体型系数");
        add("fargo_soul.configuration.allow_creatures_that_spawn_through_unnatural_paths_to_carry_souls", "Allow non-naturally spawned creatures to carry souls", "是否允许非自然途径生成的生物携带魂石");
        add("fargo_soul.configuration.allow_creatures_that_spawn_through_unnatural_paths_to_drop_souls", "Allow non-naturally spawned creatures to drop souls", "是否允许非自然途径生成的生物掉落魂石");
        add("fargo_soul.configuration.allow_friendly_mob_soul", "Allow friendly mobs to generate souls", "是否允许友善生物生成魂石");
        add("fargo_soul.configuration.allow_hostile_mob_soul", "Allow hostile mobs to generate souls", "是否允许敌人生成魂石");
        add("fargo_soul.configuration.cosmic_crucible_size", "Cosmic Crucible item variety capacity", "宇宙坩埚的物品种类数量");
        add("fargo_soul.configuration.cosmic_crucible_item_rendering", "Enable item rendering in Cosmic Crucible", "是否开启宇宙坩埚容器物品渲染");
        add("fargo_soul.configuration.cosmic_crucible_black_hole_event_horizon_rendering", "Enable Cosmic Crucible black hole event horizon rendering", "是否开启宇宙坩埚黑洞事件视界渲染");
        add("fargo_soul.configuration.embed_a_child_soul_in_the_item_tooltip", "Embed child souls in item tooltips", "是否在物品提示中嵌入子魂石");
        add("fargo_soul.configuration.creature_soul_rendering", "Render souls carried by creatures", "是否渲染生物携带的魂石");
        add("fargo_soul.configuration.item_render_scaling", "Enable item render scaling", "是否开启物品渲染缩放");
        add("fargo_soul.configuration.show_soul_tooltip", "Show soul information", "是否显示魂石信息");
        add("fargo_soul.configuration.show_soul_tooltip_scale", "Soul info scale", "魂石信息缩放比例");
        add("fargo_soul.configuration.show_soul_tooltip_x_offset", "Soul info X offset", "魂石信息X轴偏移");
        add("fargo_soul.configuration.show_soul_tooltip_y_offset", "Soul info Y offset", "魂石信息Y轴偏移");
        add("fargo_soul.configuration.information_interval", "Soul info display interval", "魂石信息显示间隔");
        add("fargo_soul.configuration.soul_info_max_render_time", "Soul info max render time", "魂石信息最大显示时间");
        add("fargo_soul.configuration.resident_show_soul_information", "Always show soul information", "是否常驻显示魂石信息");
        add("fargo_soul.configuration.black_soul_list", "Creature soul blacklist", "生物魂石黑名单");
        add("itemGroup.fargo_soul", "Fargo Soul", "Fargo 魂石");
        add("curios.identifier.soul", "Soul", "魂");
        add("key.shift.tooltip.1", "Hold [", "按住 [");
        add("key.shift.tooltip.2", "] to view summary", "] 可查看概要");
        add("effect.fargo_soul.lead_poisoning", "Lead Poisoning", "铅中毒");
        add("effect.fargo_soul.oil", "Oiled", "浸油");
        add("effect.fargo_soul.orichalcum_poisoning", "Orichalcum Poisoning", "山铜中毒");
        add("effect.fargo_soul.shadow_fire", "Shadowflame", "暗影焰");
        add("effect.fargo_soul.midas", "Midas", "迈达斯");
        add("block.fargo_soul.cosmic_crucible", "Cosmic Crucible", "宇宙坩埚");
        add("item.fargo_soul.soul", "Incorporeal Soul", "无形之魂");
        add("item.fargo_soul.terra_soul", "Terra Soul", "泰拉之魂");
        add("item.fargo_soul.terra_soul.attribute.1", "Gains an aura that fires various barrages", "获得一个可以发射各种弹幕的光环");
        add("item.fargo_soul.terra_soul.attribute.2", "Gain extra crit rate when picking up items; villagers provide more discounts", "拾取物品时获得额外暴击率，村民可提供更多折扣");
        add("item.fargo_soul.terra_soul.attribute.3", "Crits and parries fire powerful lightning, reduces debuff damage, weapons become larger", "暴击和格挡会发射强大的闪电，减少受到的减益伤害，武器变大");
        add("item.fargo_soul.terra_soul.attribute.4", "Increases crit rate when attacking, increases item pickup range", "攻击时增加暴击率，增加物品吸取范围");
        add("item.fargo_soul.terra_soul.attribute.5", "Gain defense buff when not attacking, gain attack buff when attacking", "不攻击时获得防御增益，攻击时获得攻击增益");
        add("item.fargo_soul.terra_soul.attribute.6", "The wielder has a lifesteal aura, increases damage taken, fires Chlorophyte Crystals at nearby enemies", "持有者拥有吸取生命的光环，增加受到的伤害，向附近的敌人发射叶绿水晶");
        add("item.fargo_soul.terra_soul.attribute.7", "Mushroom healing is enhanced and provides buffs, attacks inflict multiple debuffs", "蘑菇治疗得到强化并提供增益，持有者的攻击造成多种减益");
        add("item.fargo_soul.terra_soul.attribute.8", "The wielder reflects contact damage, minions can crit", "持有者反射接触伤害，持有者的随从可以暴击");
        add("item.fargo_soul.terra_soul.attribute.9", "Increases projectile attributes based on movement speed", "根据持有者移速增加射弹各种属性");
        add("item.fargo_soul.terra_soul.attribute.10", "Can summon Forbidden Storms, healing is increased, revives and cleanses debuffs when HP drops to 0", "持有者可召唤禁戒风暴，治疗会恢复更多，生命值降低至0时复活并净化减益");
        add("item.fargo_soul.terra_soul.attribute.11", "Gain an invincible Shadow Dash every 4s, increases projectile attributes based on speed, killing enemies may drop bone chunks", "持有者每4秒获得一次无敌的暗影冲刺，根据移速增加射弹各种属性，屠戮敌人可能会掉落骨块");
        add("item.fargo_soul.terra_soul.attribute.12", "Allows soul siphoning, increases healing and mount attributes, consecutive attacks gain extra damage", "允许吸取灵魂，增加持有者的治疗和坐骑属性，连续攻击会获得额外伤害");
        add("item.fargo_soul.terra_soul.attribute.13", "Defeated enemies may drop extra loot", "持有者击败的敌人可能会掉落额外的战利品");
        add("item.fargo_soul.terra_soul.attribute.14", "Attacks occasionally fire moons that explode into Lunar Flare", "持有者攻击偶尔会向敌人发射月亮并爆炸产生月亮强化焰");
        add("item.fargo_soul.terra_soul.attribute.15", "Increases movement speed and acceleration, reduces momentum, Stardust Stasis cooldown reduced to 60s", "增加持有者的移动速度 and 加速度并降低持有者的动量，星尘静滞冷却时间降低至60秒");
        add("item.fargo_soul.terra_soul.tooltip.1", "\"The Master of Terra, witnessed by Heaven and Earth\"", "“泰拉之主，天地共证”");
        add("item.fargo_soul.cosmic_power", "Cosmic Power", "宇宙之力");
        add("item.fargo_soul.cosmic_power.attribute.1", "Enhanced Solar - Solar energy build-up increased to 40% of damage dealt", "强化-耀斑-攻击时积攒的日曜能力提升至40%伤害值");
        add("item.fargo_soul.cosmic_power.attribute.2", "Enhanced Stardust - Time freeze duration extended to 10 seconds", "强化-星尘-时间冻结持续时间延长至10秒");
        add("item.fargo_soul.cosmic_power.attribute.3", "Enhanced Nebula - Nebula shot interval reduced to 2s, damage increased to 150%", "强化-星云-星云射击间隔降低至2秒，伤害提升至150%");
        add("item.fargo_soul.cosmic_power.attribute.4", "Enhanced Vortex - Teleport distance increased to 1024 blocks", "强化-星旋-传送距离提升至1024格");
        add("item.fargo_soul.cosmic_power.attribute.5", "Enhanced Meteor - Chance to summon meteor shower increased to 80%", "强化-流星-召唤流星雨的概率提升至80%");
        add("item.fargo_soul.cosmic_power.attribute.6", "Enhanced Wizard - Orbit speed of Enchantments increased", "强化-巫师-魔石的环绕速度增加");
        add("item.fargo_soul.cosmic_power.attribute.7", "Attacks randomly generate a Lunar Flare for 3s, refreshes duration on repeat", "攻击时随机产生一种以下的月亮强化焰，持续3秒，重复获得时刷新持续时间");
        add("item.fargo_soul.cosmic_power.attribute.8", "Solar Flare: +15% Damage Reduction", "耀斑强化焰：+15%伤害减免");
        add("item.fargo_soul.cosmic_power.attribute.9", "Stardust Flare: +25% Damage", "星尘强化焰：+25%伤害");
        add("item.fargo_soul.cosmic_power.attribute.10", "Nebula Flare: +5 HP/s Life Regen", "星云强化焰：+5每秒生命再生");
        add("item.fargo_soul.cosmic_power.attribute.11", "Vortex Flare: +25% Critical Strike Chance", "星旋强化焰：+25%暴击率");
        add("item.fargo_soul.cosmic_power.attribute.12", "Meteor Flare: +60 Max Health", "流星强化焰：+60点最大生命值");
        add("item.fargo_soul.cosmic_power.tooltip.1", "\"Existing since the Big Bang\"", "“自宇宙大爆炸以来就一直存在”");
        add("item.fargo_soul.blaze_soul", "Solar Enchantment", "耀斑魔石");
        add("item.fargo_soul.blaze_soul.attribute.1", "When not in Solar Power mode, attacks build Solar Energy equal to 25% of damage dealt", "未获得日耀之力时，持有者攻击时积攒相当于25%伤害值的日耀能量");
        add("item.fargo_soul.blaze_soul.attribute.2", "Max Solar Energy is [2000 + 2000% of max HP], provides up to 40% DR based on energy level", "日耀能量最大值为[2000+2000%佩戴者最大生命值]，根据积攒比例产生日曜护盾，常态下可额外提供最高40%伤害减免");
        add("item.fargo_soul.blaze_soul.attribute.3", "Gain Solar Power when energy is maxed, granting effects during the duration", "日耀能量达到最大值时获得日耀之力，日耀之力持续期间获得以下效果");
        add("item.fargo_soul.blaze_soul.attribute.4", "Consumes 100 energy to release Solar Eruption on hit, dealing [275% damage + 2.5% target max HP] fire damage", "对敌人造成伤害时会消耗100日耀能量释放日耀喷发，对攻击范围内的所有敌人额外造成[275%造成伤害+2.5%目标最大生命值]的火焰伤害");
        add("item.fargo_soul.blaze_soul.attribute.5", "Loses 2.5% max energy per second, Solar Shield effect doubles, gain 10% max HP damage block, knockback immunity", "每秒流失2.5%最大日曜能量，日曜护盾效果翻倍，获得相当于10%持有者最大生命值的伤害格挡，免疫击退");
        add("item.fargo_soul.blaze_soul.attribute.6", "Lose Solar Power when energy is depleted", "日耀能量耗尽时失去日耀之力");
        add("item.fargo_soul.blaze_soul.tooltip.1", "\"A hot pebble\"", "“烫手魔石”");
        add("item.fargo_soul.stardust_soul", "Stardust Enchantment", "星尘魔石");
        add("item.fargo_soul.stardust_soul.attribute.1", "Press 'Freeze' to freeze time for 6 seconds; 120s cooldown", "按下“冻结”键后会冻结时间，持续6秒，该效果有120秒冷却时间");
        add("item.fargo_soul.stardust_soul.attribute.2", "Damage dealt increased to 300% during time freeze", "时间冻结期间，持有者造成的伤害提升至300%");
        add("item.fargo_soul.stardust_soul.tooltip.1", "\"You have become a Stand User\"", "“你成为了替身使者”");
        add("item.fargo_soul.nebula_soul", "Nebula Enchantment", "星云魔石");
        add("item.fargo_soul.nebula_soul.attribute.1", "Summons Nebula Shots dealing [8 + 2% target max HP] magic damage; 3s cooldown", "召唤星云射击，对敌人造成[8+2%目标最大生命值]的魔法伤害，该效果有3秒冷却时间");
        add("item.fargo_soul.nebula_soul.attribute.2", "Nebula shots distort target's position and heal wielder for the damage dealt", "星云射击命中敌人时，略微扭曲敌人的位置，并为持有者恢复等同于星云射击造成伤害的生命值");
        add("item.fargo_soul.nebula_soul.tooltip.1", "\"The Pillars of Creation shine upon you\"", "“创生之柱照耀着你”");
        add("item.fargo_soul.vortex_soul", "Vortex Enchantment", "星旋魔石");
        add("item.fargo_soul.vortex_soul.attribute.1", "Press 'Teleport' to blink to your cursor's position", "按下“传送”键传送至目视的位置");
        add("item.fargo_soul.vortex_soul.attribute.2", "Generates a vortex at the destination that attracts and damages enemies", "在传送的目标位置产生一个漩涡，持续吸引并伤害附近的敌人");
        add("item.fargo_soul.vortex_soul.attribute.3", "Max teleport distance is 512 blocks", "最大传送距离为512格，大于此距离无法传送");
        add("item.fargo_soul.vortex_soul.attribute.4", "Teleport cooldown is 20 seconds", "传送冷却时间为20秒");
        add("item.fargo_soul.vortex_soul.tooltip.1", "\"Ripping reality apart\"", "“撕裂现实”");
        add("item.fargo_soul.meteor_soul", "Meteor Enchantment", "流星魔石");
        add("item.fargo_soul.meteor_soul.attribute.1", "Increases move speed by 15%, sneak to greatly increase fall speed", "增加15%移动速度，按下潜行键大幅增加下落速度");
        add("item.fargo_soul.meteor_soul.attribute.2", "20% chance to summon meteor shower on attack; 1s cooldown", "攻击时有20%概率召唤流星雨，该效果有1秒冷却时间");
        add("item.fargo_soul.meteor_soul.tooltip.1", "\"Drop a draco on 'em\"", "《Drop a draco on 'em》");
        add("item.fargo_soul.wizard_soul", "Wizard Enchantment", "巫师魔石");
        add("item.fargo_soul.wizard_soul.attribute.1", "Causes orbiting Enchantments to glow", "让环绕着持有者的魔石发光");
        add("item.fargo_soul.wizard_soul.attribute.2", "The wielder can no longer be pushed", "持有者不再会被推动");
        add("item.fargo_soul.wizard_soul.tooltip.1", "\"We love casting spells\"", "“我们爱施放魔法”");
        add("item.fargo_soul.death_power", "Power of Death", "死亡之力");
        add("item.fargo_soul.death_power.attribute.1", "Enhanced Ancient Shadow - Debuff chance increased to 100%", "强化-远古暗影-施加减益的概率提升至100%");
        add("item.fargo_soul.death_power.attribute.2", "Enhanced Crystal Assassin - Slowness level +1, duration extended to 7s", "强化-水晶刺客-减速效果的等级+1，持续时间延长至7秒");
        add("item.fargo_soul.death_power.attribute.3", "Enhanced Dark Artist - Fireball chance increased, arrow damage increased to 25% damage dealt", "强化-暗黑艺术-召唤火球的概率提升，箭矢伤害提升至25%造成伤害");
        add("item.fargo_soul.death_power.attribute.4", "Enhanced Spooky - Minion Shadowflame level +1", "强化-阴森-仆从造成的暗影焰效果等级+1");
        add("item.fargo_soul.death_power.attribute.5", "Enhanced Necro - More bones dropped, killing undead heals 2% max HP", "强化-死灵-爆出更多骨头，杀死亡灵生物额外恢复2%持有者最大生命值的生命值");
        add("item.fargo_soul.death_power.attribute.6", "Enhanced Ninja - Melee attack stack limit increased to 500%", "强化-忍者-近战攻击力的叠加上限提升至500%");
        add("item.fargo_soul.death_power.attribute.7", "Enhanced Shinobi - Collision deals extra 2% target max HP damage, knockback increased", "强化-渗透忍者-撞击额外造成2%目标最大生命值的伤害，击退力度提升");
        add("item.fargo_soul.death_power.attribute.8", "Gain Shadow Dash with a 4s cooldown", "获得暗影冲刺，这个效果有4秒冷却时间");
        add("item.fargo_soul.death_power.attribute.9", "Shadow Dash provides 0.5s of invincibility", "使用暗影冲刺会把玩家笼罩在阴影中，使持有者在0.5秒内无敌");
        add("item.fargo_soul.death_power.attribute.10", "Dashing through enemies inflicts Death Mark, increasing damage taken to 150% for 5s", "使用暗影冲刺冲过敌人会对其造成伤害并造成死亡标记，使持有者在5秒内对敌人造成的伤害提升至150%");
        add("item.fargo_soul.death_power.attribute.11", "Shadow Dash releases a burst of bones", "使用暗影冲刺会向持有者周围发射一连串骨头");
        add("item.fargo_soul.death_power.attribute.12", "Attacks inflict Shadowflame", "持有者攻击时造成暗影焰");
        add("item.fargo_soul.death_power.tooltip.1", "\"Dark, darker, yet darker\"", "“黑暗，更黑暗，还是更黑暗”");
        add("item.fargo_soul.ancient_shadow_soul", "Ancient Shadow Enchantment", "远古暗影魔石");
        add("item.fargo_soul.ancient_shadow_soul.attribute.1", "Attacks have a chance to inflict Darkness or Blindness", "持有者攻击有几率为目标施加黑暗或失明减益");
        add("item.fargo_soul.ancient_shadow_soul.attribute.2", "Debuff chance increased to 100% in dark environments", "持有者身处黑暗的环境下，施加减益的概率提升至100%");
        add("item.fargo_soul.ancient_shadow_soul.attribute.3", "Damage increased to 175% against enemies with Darkness or Blindness", "持有者攻击受黑暗或失明的目标时，造成的伤害提升至175%");
        add("item.fargo_soul.ancient_shadow_soul.attribute.4", "Immunity to Darkness and Blindness", "免疫黑暗或失明");
        add("item.fargo_soul.ancient_shadow_soul.tooltip.1", "\"Ancient, yet very practical\"", "“十分古老，却非常实用”");
        add("item.fargo_soul.crystal_assassin_soul", "Crystal Assassin Enchantment", "水晶刺客魔石");
        add("item.fargo_soul.crystal_assassin_soul.attribute.1", "Grants dash ability", "使持有者获得冲刺能力");
        add("item.fargo_soul.crystal_assassin_soul.attribute.2", "First attack on an enemy deals 220% damage and slows for 3s", "持有者首次攻击一名敌人时，造成的伤害提升至220%，并施加减速效果持续3秒");
        add("item.fargo_soul.crystal_assassin_soul.tooltip.1", "\"To the top\"", "“登顶”");
        add("item.fargo_soul.dark_artist_soul", "Dark Artist Enchantment", "暗黑艺术家魔石");
        add("item.fargo_soul.dark_artist_soul.attribute.1", "Chance to summon fireballs on attack", "持有者攻击时有概率召唤火球攻击目标");
        add("item.fargo_soul.dark_artist_soul.attribute.2", "Summons a rain of arrows dealing 15% of damage dealt; 10s cooldown", "持有者攻击时在目标头上召唤一堆箭矢作为辅助攻击，箭矢伤害基础为15%造成伤害，该效果有10秒冷却时间");
        add("item.fargo_soul.dark_artist_soul.attribute.3", "Inflicts Darkness and Blindness on attackers", "持有者被攻击时，对攻击者造成黑暗和失明减益");
        add("item.fargo_soul.dark_artist_soul.tooltip.1", "\"There is more to shadows than what is seen\"", "“阴影蕴含之物远超其表象”");
        add("item.fargo_soul.gloomy_soul", "Spooky Enchantment", "阴森魔石");
        add("item.fargo_soul.gloomy_soul.attribute.1", "Minion attacks inflict Shadowflame", "持有者的仆从攻击附加暗影焰");
        add("item.fargo_soul.gloomy_soul.tooltip.1", "\"Soul melted since 1902\"", "“自1902年以来融化的灵魂”");
        add("item.fargo_soul.necromancer_soul", "Necro Enchantment", "死灵魔石");
        add("item.fargo_soul.necromancer_soul.attribute.1", "Chance to burst bones when damaged, dealing damage to enemies", "持有者被攻击时有几率爆出一堆骨头并对敌人造成伤害");
        add("item.fargo_soul.necromancer_soul.attribute.2", "Skeletons and Wither Skeletons guaranteed to drop skulls", "持有者杀死骷髅或凋零骷髅必定额外掉落对应头颅");
        add("item.fargo_soul.necromancer_soul.attribute.3", "Killing undead creatures heals wielder for 20% of target max HP", "持有者杀死的目标为亡灵生物时，为持有者恢复20%目标最大生命值的生命值");
        add("item.fargo_soul.necromancer_soul.tooltip.1", "\"Welcome to the Bone Zone\"", "“欢迎来到骸骨领域”");
        add("item.fargo_soul.ninja_soul", "Ninja Enchantment", "忍者魔石");
        add("item.fargo_soul.ninja_soul.attribute.1", "Reduces detection range of enemies", "降低目标发现持有者的范围");
        add("item.fargo_soul.ninja_soul.attribute.2", "Melee damage builds up to 300%; reset after attacking", "近战攻击力逐渐提高至300%，攻击后清空增益");
        add("item.fargo_soul.ninja_soul.tooltip.1", "\"Waiting for the right moment...\"", "“等待正确的时机......”");
        add("item.fargo_soul.penetrating_ninja_soul", "Shinobi Infiltrator Enchantment", "渗透忍者魔石");
        add("item.fargo_soul.penetrating_ninja_soul.attribute.1", "Grants dash ability", "使持有者获得冲刺能力");
        add("item.fargo_soul.penetrating_ninja_soul.attribute.2", "Colliding with enemies during dash deals 10% max HP wither damage and massive knockback", "冲刺时撞击敌人，造成10%持有者最大生命值的凋零伤害与大量击退");
        add("item.fargo_soul.penetrating_ninja_soul.attribute.3", "Invincibility and wall-phasing for 1s after dashing; 20s cooldown", "持有者冲刺后的1秒内免疫一切伤害并可以穿过墙壁，该效果有20秒冷却时间");
        add("item.fargo_soul.penetrating_ninja_soul.tooltip.1", "\"The village hidden in walls\"", "“藏匿于墙中的村庄”");
        add("item.fargo_soul.earth_power", "Power of Earth", "大地之力");
        add("item.fargo_soul.earth_power.attribute.1", "Enhanced Adamantite - +15% move speed at max attack speed stacks", "强化-精金-攻击速度增益达到最大值时，移动速度额外提升15%");
        add("item.fargo_soul.earth_power.attribute.2", "Enhanced Cobalt - Reduced explosion CD, increased radius and damage, longer Oiled duration", "强化-钴蓝-爆炸冷却减少，爆炸范围提升，爆炸伤害提升，延长爆炸所施加浸油减益的时间");
        add("item.fargo_soul.earth_power.attribute.3", "Enhanced Mithril - Attack speed buff duration increased to 6s", "强化-秘银-攻击速度增益的持续时间提升至6秒");
        add("item.fargo_soul.earth_power.attribute.4", "Enhanced Orichalcum - Increased petal chance, Orichalcum Poisoning level +1", "强化-山铜-召唤花瓣的概率提升，施加山铜中毒的等级+1");
        add("item.fargo_soul.earth_power.attribute.5", "Enhanced Palladium - Increased life regen chance, max life regen level +1", "强化-钯金-获取生命恢复增益的概率提升，生命恢复增益的等级上限+1");
        add("item.fargo_soul.earth_power.attribute.6", "Enhanced Titanium - Titanium Shield knocks back nearby enemies when blocking", "强化-钛金-钛金护盾抵挡伤害时，击退周围的目标");
        add("item.fargo_soul.earth_power.attribute.7", "Build Earth Energy after 2s of not attacking; consumed on attack", "不攻击2秒后会积聚大地能量，攻击会消耗能量");
        add("item.fargo_soul.earth_power.attribute.8", "At max energy: +100% Attack Speed, +5 HP/s Regen, +25% DR", "攻击速度，生命回复，伤害减免会随能量积攒而增加，至多增加100%攻击速度，每秒5点生命恢复，25%伤害减免");
        add("item.fargo_soul.earth_power.attribute.9", "Attacks deal bonus damage based on energy, up to 40%", "充能后攻击会造成攻击伤害一定比例的额外伤害，随能量积攒而增加比例，至多40%");
        add("item.fargo_soul.earth_power.tooltip.1", "\"Gaia's blessing shines upon you\"", "“盖亚的祝福照耀着你”");
        add("item.fargo_soul.adamantite_soul", "Adamantite Enchantment", "精金魔石");
        add("item.fargo_soul.adamantite_soul.attribute.1", "Each attack grants 5% attack speed, max 8 stacks; reset after 5s", "持有者每次攻击会提高5%攻击速度，最高叠加8层，5秒不攻击清空");
        add("item.fargo_soul.adamantite_soul.attribute.2", "At max stacks, attacks have a chance to cause targets to lose aggro", "攻击速度增益达到最大值时，持有者的攻击有概率使目标丢失索敌");
        add("item.fargo_soul.adamantite_soul.tooltip.1", "\"Chaos\"", "“混乱”");
        add("item.fargo_soul.cobalt_soul", "Cobalt Enchantment", "钴蓝魔石");
        add("item.fargo_soul.cobalt_soul.attribute.1", "Inflicts Oiled on nearby targets", "对持有者附近的目标施加浸油减益");
        add("item.fargo_soul.cobalt_soul.attribute.2", "Oiled targets take greatly increased fire damage", "被浸油影响的目标受到的火焰伤害大幅增加");
        add("item.fargo_soul.cobalt_soul.attribute.3", "Generate a small explosion and apply Oiled when damaged; 3s cooldown", "受到伤害时，在持有者位置产生小爆炸，并对附近的目标施加浸油减益，该效果有3秒冷却时间");
        add("item.fargo_soul.cobalt_soul.attribute.4", "Immunity to Oiled", "免疫浸油");
        add("item.fargo_soul.cobalt_soul.tooltip.1", "\"Can't believe it's not Palladium\"", "“真不敢相信这竟然不是钯金”");
        add("item.fargo_soul.mithril_soul", "Mithril Enchantment", "秘银魔石");
        add("item.fargo_soul.mithril_soul.attribute.1", "Attacking after 5s of idle time grants +50% attack speed", "持有者在5秒不攻击后开始攻击会获得攻击速度增益，提升50%攻击速度");
        add("item.fargo_soul.mithril_soul.attribute.2", "Buff lost 3s after attacking", "持有者攻击目标后3秒失去增益");
        add("item.fargo_soul.mithril_soul.tooltip.1", "\"Weapon knowledge seeps into your mind\"", "“你感觉武器的知识渗透进你的脑海中”");
        add("item.fargo_soul.orichalcum_soul", "Orichalcum Enchantment", "山铜魔石");
        add("item.fargo_soul.orichalcum_soul.attribute.1", "Chance to summon petals on hit dealing [1 + 5% damage] magic damage and 5s Orichalcum Poisoning", "持有者攻击时有概率召唤花瓣落到目标的身上，造成额外[1+5%造成伤害]的魔法伤害并施加5秒山铜中毒减益");
        add("item.fargo_soul.orichalcum_soul.attribute.2", "Orichalcum Poisoning deals continuous damage and increases poison damage taken to 350%", "山铜中毒会对目标持续造成魔法伤害，并将目标受到的所有毒性伤害提升至350%");
        add("item.fargo_soul.orichalcum_soul.attribute.3", "Immunity to Orichalcum Poisoning", "免疫山铜中毒");
        add("item.fargo_soul.orichalcum_soul.tooltip.1", "\"Nature blesses you\"", "“自然祝福着你”");
        add("item.fargo_soul.palladium_soul", "Palladium Enchantment", "钯金魔石");
        add("item.fargo_soul.palladium_soul.attribute.1", "Attacks have a chance to grant 2s of Regeneration", "持有者攻击时有概率给予2秒生命恢复增益");
        add("item.fargo_soul.palladium_soul.attribute.2", "Stacks refresh duration and increase Regen level, up to level 3", "每次获取增益会刷新生命恢复的持续时间，并提升生命恢复增益的等级，上限3级");
        add("item.fargo_soul.palladium_soul.attribute.3", "Gain Absorption for every 10 HP recovered", "持有者每恢复10生命值额外获取伤害吸收增益");
        add("item.fargo_soul.palladium_soul.tooltip.1", "\"You feel your wounds slowly healing\"", "“你感到你的伤口在慢慢愈合”");
        add("item.fargo_soul.titanium_soul", "Titanium Enchantment", "钛金魔石");
        add("item.fargo_soul.titanium_soul.attribute.1", "Generate a Titanium Shield after 20s of no damage, blocking next hit", "持有者每20秒不受伤害会生成一个钛金护盾，免疫下次受到伤害");
        add("item.fargo_soul.titanium_soul.attribute.2", "If shield is down, gain up to 25% move speed based on missing health", "钛金护盾未生成时，根据持有者已损生命值比例提升移动速度，最高增加25%移动速度");
        add("item.fargo_soul.titanium_soul.tooltip.1", "\"Who needs to dodge with absolute defense?\"", "“有了绝对防御后，谁还需要躲避呢？”");
        add("item.fargo_soul.forest_power", "Power of Forest", "森林之力");
        add("item.fargo_soul.forest_power.attribute.1", "Enhanced Ebonwood - Corruption limit increased to 200", "强化-乌木-腐化目标的上限提升至200点");
        add("item.fargo_soul.forest_power.attribute.2", "Enhanced Palm Wood - Attacks on burning targets may cause explosions", "强化-棕榈木-持有者攻击燃烧的目标时，有概率产生小型爆炸");
        add("item.fargo_soul.forest_power.attribute.3", "Enhanced Pearlwood - Additional critical strike check count +1", "强化-珍珠木-额外进行的暴击判定次数+1");
        add("item.fargo_soul.forest_power.attribute.4", "Enhanced Boreal Wood - Increases snowball generation speed", "强化-针叶木-提升产生雪球的速度");
        add("item.fargo_soul.forest_power.attribute.5", "Enhanced Rich Mahogany - Increases traction strength", "强化-红木-提升牵引力度");
        add("item.fargo_soul.forest_power.attribute.6", "Enhanced Shadewood - Life siphoned increased to 3 points", "强化-阴影木-汲取的生命值提升至3点");
        add("item.fargo_soul.forest_power.attribute.7", "Enhanced Wood - Further increases discounts", "强化-木-进一步提升折扣");
        add("item.fargo_soul.forest_power.attribute.8", "Grants a Wither Aura", "使持有者拥有凋零光环");
        add("item.fargo_soul.forest_power.attribute.9", "Hitting enemies in the aura fires snowballs; 0.25s cooldown", "击中光环内的敌人时会发射雪球，该效果有0.25秒冷却时间");
        add("item.fargo_soul.forest_power.attribute.10", "Attacking Withered enemies deals 15 bonus damage", "持有者攻击被凋零效果影响的敌人时，造成的伤害额外提升15点");
        add("item.fargo_soul.forest_power.attribute.11", "Gain 30% DR and 200% Thorns while in the air; 8s cooldown", "在空中时，获得30%伤害减免和200%荆棘效果，该效果有8秒冷却时间");
        add("item.fargo_soul.forest_power.attribute.12", "Gain 20% DR against enemies you have previously killed", "持有者受到曾击杀过的目标伤害时，获得20%伤害减免");
        add("item.fargo_soul.forest_power.tooltip.1", "\"Very hard\"", "“很硬”");
        add("item.fargo_soul.ebony_wood_soul", "Ebonwood Enchantment", "乌木魔石");
        add("item.fargo_soul.ebony_wood_soul.attribute.1", "Nearby targets are gradually Corrupted, up to 100 points", "在持有者周围的目标会被逐渐腐化，腐化值上限为100点");
        add("item.fargo_soul.ebony_wood_soul.attribute.2", "Each point reduces target damage by 0.05% and increases damage taken by 0.1%", "每点腐化值降低目标对持有者的伤害0.05%，提升持有者对目标的伤害0.1%");
        add("item.fargo_soul.ebony_wood_soul.attribute.4", "Immunity to Corruption", "免疫腐化");
        add("item.fargo_soul.ebony_wood_soul.tooltip.1", "\"Potential not fully tapped\"", "“潜力未完全开发”");
        add("item.fargo_soul.palm_wood_soul", "Palm Wood Enchantment", "棕榈木魔石");
        add("item.fargo_soul.palm_wood_soul.attribute.1", "Attacks ignite targets or extend burn duration up to 30s", "持有者攻击时，点燃目标或延长目标的燃烧时间，至多延长至30秒");
        add("item.fargo_soul.palm_wood_soul.attribute.2", "Fire damage taken by nearby enemies increased to 150%", "持有者周围的目标受到的火焰伤害提升至150%");
        add("item.fargo_soul.palm_wood_soul.tooltip.1", "\"Surprisingly peaceful\"", "“出奇的宁静”");
        add("item.fargo_soul.pearl_wood_soul", "Pearlwood Enchantment", "珍珠木魔石");
        add("item.fargo_soul.pearl_wood_soul.attribute.1", "Crit damage multiplier increased to 130%", "持有者攻击暴击时，暴击伤害系数提升至130%");
        add("item.fargo_soul.pearl_wood_soul.attribute.2", "Non-crits have a 25% chance to be re-rolled as a crit", "持有者攻击没有暴击时，额外进行25%概率的暴击判定");
        add("item.fargo_soul.pearl_wood_soul.tooltip.1", "\"Too little, too late...\"", "“太少了，太晚了……”");
        add("item.fargo_soul.pine_wood_soul", "Boreal Wood Enchantment", "针叶木魔石");
        add("item.fargo_soul.pine_wood_soul.attribute.1", "Generates snowballs above your head to attack random nearby enemies", "持有者的头顶会产生雪球攻击周围随机目标");
        add("item.fargo_soul.pine_wood_soul.tooltip.1", "\"Cold and cool\"", "“又冷又酷”");
        add("item.fargo_soul.rose_wood_soul", "Rich Mahogany Enchantment", "红木魔石");
        add("item.fargo_soul.rose_wood_soul.attribute.1", "Attacking airborne targets pulls them slightly towards you", "持有者攻击空中目标时，会将目标向持有者方向牵引一小段距离");
        add("item.fargo_soul.rose_wood_soul.attribute.2", "Immunity to traction", "免疫牵引");
        add("item.fargo_soul.rose_wood_soul.tooltip.1", "\"Guaranteed to hook you\"", "“保证钩到你”");
        add("item.fargo_soul.shadow_wood_soul", "Shadewood Enchantment", "阴影木魔石");
        add("item.fargo_soul.shadow_wood_soul.attribute.1", "Apply a Siphon Mark to a random nearby target every 5s", "每5秒为持有者周围随机一个目标附加汲取标记");
        add("item.fargo_soul.shadow_wood_soul.attribute.2", "When a marked target attacks you, siphon 2 HP and remove mark", "带有汲取标记的目标攻击持有者时，持有者将汲取目标2点生命值并移除标记");
        add("item.fargo_soul.shadow_wood_soul.tooltip.1", "\"Surprisingly clean\"", "“出奇的干净”");
        add("item.fargo_soul.wood_soul", "Wood Enchantment", "木魔石");
        add("item.fargo_soul.wood_soul.attribute.1", "Increased villager discounts, permanent good reputation in villages", "村民折扣增加，持有者在村庄中永远拥有好声望");
        add("item.fargo_soul.wood_soul.tooltip.1", "\"A trick hated by shopkeepers\"", "“被店主们讨厌的诡计”");
        add("item.fargo_soul.wood_soul.tooltip.2", "\"Humble beginnings...\"", "“卑微的开始……”");
        add("item.fargo_soul.life_power", "Power of Life", "生命之力");
        add("item.fargo_soul.life_power.attribute.1", "Enhanced Turtle - Increased cactus burst chance, count, and damage", "强化-乌龟-爆出仙人掌的概率提升，数量提升，伤害提升");
        add("item.fargo_soul.life_power.attribute.2", "Enhanced Bee - Bees and flower-contact healing speed increased", "强化-蜜蜂-周围蜜蜂的恢复速度加快，持有者接触花朵时恢复生命值的速度加快");
        add("item.fargo_soul.life_power.attribute.3", "Enhanced Beetle - Max Beetle Endurance +1, Max Beetle Might +2", "强化-甲虫-甲虫耐力层数上限+1，甲虫力量层数上限+2");
        add("item.fargo_soul.life_power.attribute.4", "Enhanced Pumpkin - Explosion damage increased, enemies hit drop pumpkin seeds", "强化-南瓜-南瓜的爆炸伤害提升，被爆炸伤害的目标会爆出南瓜子");
        add("item.fargo_soul.life_power.attribute.5", "Enhanced Spider - Minion crit to 40% and 200% damage, no cap on minion crit bonus", "强化-蜘蛛-仆从暴击率提升至40%，仆从暴击伤害提升至200%，仆从暴击增伤不再有上限");
        add("item.fargo_soul.life_power.attribute.6", "Provides powerful wing flight", "提供强大的翅膀飞行能力");
        add("item.fargo_soul.life_power.attribute.7", "Heal when touching flowers, spawning bees and granting 10s Ambrosia", "触碰花朵时会回复血量，同时产生大量蜜蜂，获得10秒仙馔密酒增益");
        add("item.fargo_soul.life_power.attribute.8", "Ambrosia: +30% Damage, +20% DR, and +5 HP/s Regen", "仙馔密酒增益增加30%伤害，增加20%伤害减免和5每秒生命恢复");
        add("item.fargo_soul.life_power.attribute.9", "Ambrosia increases minion crit damage to 400%", "仙馔密酒增益会使仆从的暴击伤害提升至400%");
        add("item.fargo_soul.life_power.attribute.10", "Reflects 500% contact damage", "反弹500%的接触伤害");
        add("item.fargo_soul.life_power.tooltip.1", "\"Few creatures dare defy your will\"", "“罕有生灵敢违背你的意愿”");
        add("item.fargo_soul.bee_soul", "Bee Enchantment", "蜜蜂魔石");
        add("item.fargo_soul.bee_soul.attribute.1", "Allows short flight", "允许持有者短时间飞行");
        add("item.fargo_soul.bee_soul.attribute.2", "Nearby bees recover HP and won't attack you", "使持有者附近的蜜蜂逐渐恢复生命值，蜜蜂不会攻击持有者");
        add("item.fargo_soul.bee_soul.attribute.3", "Slowly recover HP when touching flowers", "持有者接触花朵时缓慢恢复生命值");
        add("item.fargo_soul.bee_soul.attribute.4", "Nearby bees assist in attacking your target", "持有者攻击目标时，周围的蜜蜂会协同攻击目标");
        add("item.fargo_soul.bee_soul.attribute.5", "Drinking honey heals 5% max HP and summons a bee", "持有者饮用蜂蜜时，额外恢复5%持有者最大生命值的生命值并召唤一只蜜蜂");
        add("item.fargo_soul.bee_soul.attribute.6", "You cannot damage bees", "持有者不会对蜜蜂造成伤害");
        add("item.fargo_soul.bee_soul.attribute.7", "Immunity to fall damage", "免疫摔落伤害");
        add("item.fargo_soul.bee_soul.tooltip.1", "\"According to all known laws of aviation, there is no way a bee should be able to fly\"", "“根据目前所知的所有航空原理，蜜蜂应该根本不可能会飞”");
        add("item.fargo_soul.beetle_soul", "Beetle Enchantment", "甲虫魔石");
        add("item.fargo_soul.beetle_soul.attribute.1", "Allows short flight", "允许持有者短时间飞行");
        add("item.fargo_soul.beetle_soul.attribute.2", "Gain Beetle Endurance every 7s, max 2 stacks", "持有者每7秒获得1层甲虫耐力，最多叠加2层");
        add("item.fargo_soul.beetle_soul.attribute.3", "Each stack gives +15% DR; lost when damaged", "每层甲虫耐力增加持有者15%伤害减免，每次受到伤害时失去1层甲虫耐力");
        add("item.fargo_soul.beetle_soul.attribute.4", "Gain Beetle Might on hit, max 4 stacks", "持有者攻击目标时获得1层甲虫力量，最多叠加4层");
        add("item.fargo_soul.beetle_soul.attribute.5", "Each stack gives +3 Armor Pen; lose 1 stack per second", "每层甲虫力量增加持有者3点护甲穿透，每秒失去1层甲虫力量");
        add("item.fargo_soul.beetle_soul.attribute.6", "Arthropods will not attack you", "节肢动物们不会主动攻击持有者");
        add("item.fargo_soul.beetle_soul.tooltip.1", "\"Invisible fecal life flows through your veins\"", "“你的血管里流淌着看不见的粪便生命”");
        add("item.fargo_soul.pumpkin_soul", "Pumpkin Enchantment", "南瓜魔石");
        add("item.fargo_soul.pumpkin_soul.attribute.1", "Plant pumpkin seeds while moving if on suitable soil", "如果脚下可以种植南瓜，持有者在移动时将会种下南瓜种子");
        add("item.fargo_soul.pumpkin_soul.attribute.2", "Stepping on ripe pumpkins causes them to explode", "踩在成熟的南瓜上时会使南瓜产生爆炸");
        add("item.fargo_soul.pumpkin_soul.attribute.3", "Speeds up pumpkin growth nearby", "加速持有者周围南瓜的生长速度");
        add("item.fargo_soul.pumpkin_soul.tooltip.1", "\"Your sudden craving for pumpkins will never be satisfied\"", "“你对南瓜的突发渴望永远不会得到满足”");
        add("item.fargo_soul.spider_soul", "Spider Enchantment", "蜘蛛魔石");
        add("item.fargo_soul.spider_soul.attribute.1", "Minions gain +20% crit rate and 150% crit damage", "使持有者的仆从获得20%暴击率和150%暴击伤害");
        add("item.fargo_soul.spider_soul.attribute.2", "Minion crit damage bonus capped at 100", "持有者仆从暴击增加的伤害上限为100点");
        add("item.fargo_soul.spider_soul.tooltip.1", "\"Arachnophobe? Kill him with spiders!\"", "“蜘蛛恐惧者？作为惩罚，让他被蜘蛛干掉吧！”");
        add("item.fargo_soul.turtle_soul", "Turtle Enchantment", "乌龟魔石");
        add("item.fargo_soul.turtle_soul.attribute.1", "Reflects 60% contact damage; scales down with distance to 10%", "持有者被目标攻击时反弹60%接触伤害，距离越远反弹的伤害越低，至多衰减至接触伤害of the 10%");
        add("item.fargo_soul.turtle_soul.attribute.2", "At <50% HP: reflects 80% damage regardless of distance with knockback", "持有者生命值低于50%时，反弹的伤害提升至80%接触伤害，反弹伤害不再随距离衰减，反弹伤害时附加击退");
        add("item.fargo_soul.turtle_soul.attribute.3", "At <25% HP: gain Shell granting 4% max HP damage block", "持有者生命值低于25%时，持有者会获得龟壳，龟壳存在时，持有者获得相当于4%最大生命值的伤害格挡");
        add("item.fargo_soul.turtle_soul.attribute.4", "Shell vanishes >25% HP or breaks on lethal hit; 120s cooldown", "龟壳会在持有者高于25%生命值时消失，或在受到大于持有者当前生命值的伤害时破碎，并完全抵挡此伤害，龟壳破碎后120秒不会再生成龟壳");
        add("item.fargo_soul.turtle_soul.attribute.5", "Damaged: chance to release cacti; kills burst into more cacti", "受到攻击时，有概率释放出一堆仙人掌，被仙人掌扎死的敌人会爆裂出更多仙人掌");
        add("item.fargo_soul.turtle_soul.attribute.6", "Immunity to cactus damage", "免疫仙人掌伤害");
        add("item.fargo_soul.turtle_soul.tooltip.1", "\"You have a sudden urge to hide in a shell\"", "“你突然有一种想躲进壳里的冲动”");
        add("item.fargo_soul.nature_power", "Power of Nature", "自然之力");
        add("item.fargo_soul.nature_power.attribute.1", "Enhanced Crimson - Siphon range increased", "强化-猩红-汲取范围提升");
        add("item.fargo_soul.nature_power.attribute.2", "Enhanced Frost - Max snowballs increased to 20", "强化-冰霜-雪球的存在上限提升至20个");
        add("item.fargo_soul.nature_power.attribute.3", "Enhanced Chlorophyte - Attack interval reduced, inflicts Poison", "强化-叶绿-攻击间隔降低，并且会对目标施加中毒");
        add("item.fargo_soul.nature_power.attribute.4", "Enhanced Lava - Burning targets nearby may explode", "强化-熔岩-持有者周围燃烧的目标有概率产生爆炸");
        add("item.fargo_soul.nature_power.attribute.5", "Enhanced Mushroom - Stews grant Mush-Power for 10s", "强化-蘑菇-持有者食用蘑菇煲后获得蘑菇力量增益持续10秒");
        add("item.fargo_soul.nature_power.attribute.6", "Enhanced Rain - Lightning chance increased during rain", "强化-雨云-在雨天时，召唤雷电的概率提升");
        add("item.fargo_soul.nature_power.attribute.7", "Nature Aura: deals damage and siphons HP every 0.5s; damage x4 if not hit for 4s", "持有者拥有一个自然光环，每过0.5秒对光环内的敌人造成伤害并吸取生命值，基础伤害为2，每4秒不受击可增加一倍伤害，最高4倍");
        add("item.fargo_soul.nature_power.attribute.8", "Summons 5 Chlorophyte Crystals firing 20 damage lasers", "召唤5个围绕持有者旋转的叶绿水晶，水晶会向敌怪发射激光，激光基础伤害为20");
        add("item.fargo_soul.nature_power.attribute.9", "Crystal hits spawn 5 mushrooms dealing 20% of laser damage", "叶绿水晶击中后会产生5个蘑菇，蘑菇伤害为激光造成伤害的20%");
        add("item.fargo_soul.nature_power.attribute.10", "Mushrooms restore +50 HP; Mush-Power increases aura size", "持有者食用蘑菇可额外恢复50点生命值，拥有蘑菇力量时增加光环大小");
        add("item.fargo_soul.nature_power.attribute.11", "Attacks slow targets", "持有者攻击会使向目标施加缓慢");
        add("item.fargo_soul.nature_power.attribute.12", "Ranged damage taken reduced by 15", "远程射弹对持有者造成的伤害降低15点");
        add("item.fargo_soul.nature_power.tooltip.1", "\"Travel through every secret corner of the wilderness\"", "“走遍荒野的每一个秘密角落”");
        add("item.fargo_soul.crimson_soul", "Crimson Enchantment", "猩红魔石");
        add("item.fargo_soul.crimson_soul.attribute.1", "Siphon 10% of health lost by nearby targets", "周围的目标每次受伤时，持有者都会汲取目标失去生命值的10%");
        add("item.fargo_soul.crimson_soul.attribute.2", "Siphon scales up to 40% based on missing health", "持有者已损生命值比例越高，汲取的生命值越多，至多汲取目标失去生命值的40%");
        add("item.fargo_soul.crimson_soul.tooltip.1", "\"Reborn from the blood of enemies\"", "“你从敌人的鲜血中重生”");
        add("item.fargo_soul.frost_soul", "Frost Enchantment", "冰霜魔石");
        add("item.fargo_soul.frost_soul.attribute.1", "Generates 1 snowball per second, up to 10", "每秒在持有者周围生成1个雪球，最多可同时存在10个");
        add("item.fargo_soul.frost_soul.attribute.2", "Fires a snowball at nearby targets every 0.25s", "每0.25秒发射1个雪球攻击附近的目标");
        add("item.fargo_soul.frost_soul.attribute.3", "Greatly increases snowball damage", "大幅提升持有者雪球的伤害");
        add("item.fargo_soul.frost_soul.attribute.4", "In cold biomes, generation and fire rate increased by 60%", "在寒冷群系时，雪球的生成和发射间隔降低60%");
        add("item.fargo_soul.frost_soul.tooltip.1", "\"Let's coat the world in a thick layer of ice\"", "“让我们给这个世界披上一层厚厚的冰衣”");
        add("item.fargo_soul.green_soul", "Chlorophyte Enchantment", "叶绿魔石");
        add("item.fargo_soul.green_soul.attribute.1", "Grants dash ability", "使持有者获得冲刺能力");
        add("item.fargo_soul.green_soul.attribute.2", "Extends flight time", "延长持有者的飞行时间");
        add("item.fargo_soul.green_soul.attribute.3", "Chlorophyte Crystal attacks nearby random targets", "产生一个跟随持有者的叶绿水晶攻击附近随机目标");
        add("item.fargo_soul.green_soul.attribute.4", "Crystal hits inflict Glowing", "叶绿水晶时对攻击的目标会施加发光效果");
        add("item.fargo_soul.green_soul.tooltip.1", "\"The essence of the jungle condenses into crystals\"", "“丛林的精华在你周围凝结成晶体”");
        add("item.fargo_soul.lava_soul", "Lava Enchantment", "熔岩魔石");
        add("item.fargo_soul.lava_soul.attribute.1", "Ignites nearby targets", "引燃持有者附近的目标");
        add("item.fargo_soul.lava_soul.attribute.2", "Immunity to Lava", "免疫熔岩");
        add("item.fargo_soul.lava_soul.tooltip.1", "\"They will feel the wrath of Hell\"", "“他们将感受到地狱的愤怒”");
        add("item.fargo_soul.mushroom_soul", "Mushroom Enchantment", "蘑菇魔石");
        add("item.fargo_soul.mushroom_soul.attribute.1", "Mushroom Stew heals an additional [4 + 10% missing HP]", "持有者食用蘑菇煲时会额外恢复[4+10%持有者已损生命值]的生命值");
        add("item.fargo_soul.mushroom_soul.attribute.2", "Enemies killed drop mushrooms", "目标被持有者击杀后，会掉落蘑菇");
        add("item.fargo_soul.mushroom_soul.tooltip.1", "\"Made with real mushrooms!\"", "“是用真的蘑菇做的！”");
        add("item.fargo_soul.rain_cloud_soul", "Rain Enchantment", "雨云魔石");
        add("item.fargo_soul.rain_cloud_soul.attribute.1", "Chance to strike targets with lightning when damaged", "受到伤害时有概率召唤雷电劈向目标");
        add("item.fargo_soul.rain_cloud_soul.attribute.2", "Immunity to lightning damage", "免疫雷击伤害");
        add("item.fargo_soul.rain_cloud_soul.tooltip.1", "\"Come again another day\"", "“改日再来”");
        add("item.fargo_soul.spirit_power", "Power of Spirit", "心灵之力");
        add("item.fargo_soul.spirit_power.attribute.1", "Enhanced Ancient Hallowed - Min melee attack strength to 50%", "强化-远古神圣-持有者近战攻击时的最低攻击强度提升至50%");
        add("item.fargo_soul.spirit_power.attribute.2", "Enhanced Forbidden - Storm duration 8s, increased range", "强化-禁戒-风暴的持续时间提升至8秒，影响范围提升");
        add("item.fargo_soul.spirit_power.attribute.3", "Enhanced Spectre - Soul Energy cap increased to 200", "强化-幽魂-持有者获取灵魂能量的上限提升至200层");
        add("item.fargo_soul.spirit_power.attribute.4", "Enhanced Hallowed - Shockwave radius increased", "强化-神圣-冲击波范围提升");
        add("item.fargo_soul.spirit_power.attribute.5", "Enhanced Tiki - Minion revive CD reduced to 180s", "强化-提基-仆从复活冷却降低至180秒");
        add("item.fargo_soul.spirit_power.attribute.6", "Healing received increased to 170%", "持有者受到的治疗量提升至170%");
        add("item.fargo_soul.spirit_power.attribute.7", "Gain 5 Soul Energy per second; excess energy heals you", "每秒获得5层灵魂能量，溢出的灵魂能量会改为治疗持有者");
        add("item.fargo_soul.spirit_power.attribute.8", "Greatly extends flight time", "大幅延长持有者的飞行时间");
        add("item.fargo_soul.spirit_power.tooltip.1", "\"Drifting away like a transcended immortal\"", "“飘飘乎如遗世独立，羽化而登仙”");
        add("item.fargo_soul.ancient_holy_soul", "Ancient Hallowed Enchantment", "远古神圣魔石");
        add("item.fargo_soul.ancient_holy_soul.attribute.1", "Min melee attack strength to 35%", "持有者近战攻击时的最低攻击强度提升至35%");
        add("item.fargo_soul.ancient_holy_soul.tooltip.1", "\"Do you have the power to wield me?\"", "“你有足够的力量驾驭我吗？”");
        add("item.fargo_soul.forbidden_soul", "Forbidden Enchantment", "禁戒魔石");
        add("item.fargo_soul.forbidden_soul.attribute.1", "Press 'Storm' to summon a sandstorm at cursor for 5s; 30s cooldown", "按下“风暴”键在持有者准星方块召唤风暴，每秒吸引风暴附近的目标，持续5秒，该效果有30秒冷却时间");
        add("item.fargo_soul.forbidden_soul.attribute.2", "Immunity to storm attraction", "免疫风暴吸引");
        add("item.fargo_soul.forbidden_soul.tooltip.1", "\"Walk like an Egyptian\"", "“走路像个埃及人”");
        add("item.fargo_soul.ghost_soul", "Spectre Enchantment", "幽魂魔石");
        add("item.fargo_soul.ghost_soul.attribute.1", "Revive at 25% HP and cleanse debuffs on death; 600s cooldown", "持有者死亡时复活，恢复25%持有者最大生命值的生命值并清除减益效果，该效果有600秒冷却时间");
        add("item.fargo_soul.ghost_soul.attribute.2", "On revive, deal 100% max HP magic damage to nearby enemies", "持有者复活时对周围所有目标造成100%持有者最大生命值的魔法伤害");
        add("item.fargo_soul.ghost_soul.attribute.3", "Attacks steal Soul Energy from targets", "持有者每次攻击时都会从目标夺取灵魂能量");
        add("item.fargo_soul.ghost_soul.attribute.4", "Each Soul Energy layer increases max HP by 1%", "每层额外的灵魂能量提升持有者1%最大生命值");
        add("item.fargo_soul.ghost_soul.attribute.5", "Each layer lost reduces max HP by 1%", "每失去一层灵魂能量降低1%最大生命值");
        add("item.fargo_soul.ghost_soul.attribute.6", "Max 100 energy, min -20 energy", "最多失去20层灵魂能量，最多获取100层灵魂能量");
        add("item.fargo_soul.ghost_soul.tooltip.1", "\"Their life force will destroy themselves\"", "“他们的生命力将毁灭他们自己”");
        add("item.fargo_soul.holy_soul", "Hallowed Enchantment", "神圣魔石");
        add("item.fargo_soul.holy_soul.attribute.1", "Healing received increased to 140%", "持有者受到的治疗提升至140%");
        add("item.fargo_soul.holy_soul.attribute.2", "Healing creates a shockwave knocking back nearby targets", "持有者受到治疗时会产生冲击波，击退附近的目标");
        add("item.fargo_soul.holy_soul.tooltip.1", "\"Bring it on\"", "《尽管放马过来》");
        add("item.fargo_soul.teke_soul", "Tiki Enchantment", "提基魔石");
        add("item.fargo_soul.teke_soul.attribute.1", "Minions revive at 25% HP on death; 300s cooldown", "持有者仆从死亡时复活，恢复25%持有者最大生命值的生命值并清除减益效果，该效果有300秒冷却时间");
        add("item.fargo_soul.teke_soul.tooltip.1", "\"Aku Aku!\"", "“Aku Aku!”");
        add("item.fargo_soul.terra_power", "Power of Terra", "泰拉之力");
        add("item.fargo_soul.terra_power.attribute.1", "Enhanced Copper - Summons two lightning bolts with 200% damage", "强化-铜-召唤两道闪电，并且伤害提升至200%");
        add("item.fargo_soul.terra_power.attribute.2", "Enhanced Iron - Increased attraction strength and range", "强化-铁-吸引强度提升，吸引范围提升");
        add("item.fargo_soul.terra_power.attribute.3", "Enhanced Lead - Lead Poisoning level +1", "强化-铅-铅中毒减益等级+1");
        add("item.fargo_soul.terra_power.attribute.4", "Enhanced Obsidian - Reduced fireball interval, increased speed", "强化-黑曜石-产生火球的间隔降低，火球的飞行速度提升");
        add("item.fargo_soul.terra_power.attribute.5", "Enhanced Silver - Parrying window +0.1s", "强化-银-额外增加0.1秒格挡判定时间");
        add("item.fargo_soul.terra_power.attribute.6", "Enhanced Tin - Min crit 20%, max extra crit 100%", "强化-锡-暴击率下限提升至20%，额外暴击率上限提升至100%");
        add("item.fargo_soul.terra_power.attribute.7", "Enhanced Tungsten - Additional +50% item size", "强化-钨-额外提升50%物品大小");
        add("item.fargo_soul.terra_power.attribute.8", "Crits may fire 40 damage lightning causing Lead Poisoning; 5s cooldown", "持有者暴击有概率发射一道闪电，闪电基础伤害为40，造成爆炸并附加铅中毒，此效果有5秒冷却");
        add("item.fargo_soul.terra_power.attribute.9", "Lightning increases crit by 10% (max 40%); max crit reduces bolt CD by 40%", "每发射一道闪电，持有者暴击率提升10%，最高提升40%暴击率，暴击率满时减少40%闪电发射冷却");
        add("item.fargo_soul.terra_power.attribute.10", "Taking damage resets crit bonus", "受到伤害时重置暴击率");
        add("item.fargo_soul.terra_power.tooltip.1", "\"The Earth grants it strength\"", "“大地赐予它力量”");
        add("item.fargo_soul.copper_soul", "Copper Enchantment", "铜魔石");
        add("item.fargo_soul.copper_soul.attribute.1", "Chance to summon lightning on attack; 2s cooldown", "持有者攻击时有概率召唤闪电攻击目标，该效果有2秒冷却时间");
        add("item.fargo_soul.copper_soul.attribute.2", "Lightning pulls nearby enemies into the strike", "如果目标周围有其他目标，会被吸引到闪电位置一同被攻击");
        add("item.fargo_soul.copper_soul.attribute.3", "Increased chance against targets in rain or water", "命中雨中或水中的目标时释放闪电的概率增加");
        add("item.fargo_soul.copper_soul.tooltip.1", "\"Its music is electric\"", "“它的音乐还是电音”");
        add("item.fargo_soul.iron_soul", "Iron Enchantment", "铁魔石");
        add("item.fargo_soul.iron_soul.attribute.1", "Attracts nearby items", "持有者会吸引周围的物品");
        add("item.fargo_soul.iron_soul.attribute.2", "Damage taken reduced by 20% for 5s after picking up an item", "拾取物品后的5秒内受到的伤害减少20%");
        add("item.fargo_soul.iron_soul.tooltip.1", "\"Strike while the iron is hot\"", "“趁热打铁”");
        add("item.fargo_soul.lead_soul", "Lead Enchantment", "铅魔石");
        add("item.fargo_soul.lead_soul.attribute.1", "Attacks have a chance to inflict Lead Poisoning", "持有者攻击有几率造成铅中毒");
        add("item.fargo_soul.lead_soul.attribute.2", "Immunity to Lead Poisoning", "免疫铅中毒");
        add("item.fargo_soul.lead_soul.tooltip.1", "\"Not recommended for consumption\"", "“不建议食用”");
        add("item.fargo_soul.obsidian_soul", "Obsidian Enchantment", "黑曜石魔石");
        add("item.fargo_soul.obsidian_soul.attribute.1", "Generates fireballs to attack nearby enemies", "持有者周围会产生火球攻击附近敌人");
        add("item.fargo_soul.obsidian_soul.attribute.2", "Better vision in lava", "持有者在熔岩中时获得更好的视野");
        add("item.fargo_soul.obsidian_soul.attribute.3", "Sets minimum armor to 8", "将持有者的护甲值下限提升至8点");
        add("item.fargo_soul.obsidian_soul.attribute.4", "Immunity to fire and lava damage", "免疫火焰与熔岩伤害");
        add("item.fargo_soul.obsidian_soul.tooltip.1", "\"The Earth is calling\"", "“大地在呼唤”");
        add("item.fargo_soul.silver_soul", "Silver Enchantment", "银魔石");
        add("item.fargo_soul.silver_soul.attribute.1", "+10 defense while blocking", "持有者举盾状态会增加10点防御力");
        add("item.fargo_soul.silver_soul.attribute.2", "Blocking within 0.2s reflects 200% damage", "持有者举盾后0.2秒抵挡攻击会反弹目标200%伤害");
        add("item.fargo_soul.silver_soul.attribute.3", "Damage increased to 150% for 1s after reflecting", "持有者反弹后1秒内造成的伤害提高至150%");
        add("item.fargo_soul.silver_soul.tooltip.1", "\"Reflection\"", "“反射”");
        add("item.fargo_soul.tin_soul", "Tin Enchantment", "锡魔石");
        add("item.fargo_soul.tin_soul.attribute.1", "Min crit chance to 10%, min crit damage to 200%", "将持有者的暴击率下限设为10%，暴击伤害下限设为200%");
        add("item.fargo_soul.tin_soul.attribute.2", "Each crit adds +10% extra crit chance, max 60%", "每次持有者暴击时都会增加10%额外暴击率，额外暴击率的最大值为60%");
        add("item.fargo_soul.tin_soul.attribute.3", "Extra crit chance halved when damaged", "持有者受伤会使额外暴击率减半");
        add("item.fargo_soul.tin_soul.tooltip.1", "\"Crits are back\"", "“暴击回归”");
        add("item.fargo_soul.tungsten_soul", "Tungsten Enchantment", "钨魔石");
        add("item.fargo_soul.tungsten_soul.attribute.1", "+50% attack reach", "持有者增加50%攻击距离");
        add("item.fargo_soul.tungsten_soul.attribute.2", "+100% size of held items", "持有者手持物品大小提升100%");
        add("item.fargo_soul.tungsten_soul.tooltip.1", "\"Bigger is better\"", "“大就是好”");
        add("item.fargo_soul.will_power", "Power of Will", "意志之力");
        add("item.fargo_soul.will_power.attribute.1", "Enhanced Gladiator - Arrow rain interval reduced to 12 attacks", "强化-角斗士-召唤箭雨的间隔降低至12次攻击");
        add("item.fargo_soul.will_power.attribute.2", "Enhanced Gold - -15% damage from Midas-afflicted enemies, Gold Ring duration to 7s", "强化-金-持有者受被迈达斯影响的敌人攻击时受到的伤害降低15%，金环持续时间提升至7秒");
        add("item.fargo_soul.will_power.attribute.3", "Enhanced Platinum - Bonus loot multiplier to x8", "强化-铂金-产生额外战利品的倍数提升至8倍");
        add("item.fargo_soul.will_power.attribute.4", "Enhanced Red Riding - Guerrilla stack limit to 15", "强化-红色骑术-游击层数上限提升至15层");
        add("item.fargo_soul.will_power.attribute.5", "Enhanced Valhalla Knight - Mounts can knock away targets on collision", "强化-英灵殿骑士-骑乘坐骑时，坐骑能够撞飞目标");
        add("item.fargo_soul.will_power.attribute.6", "Healing received increased to 125%", "持有者受到的治疗效果提升至125%");
        add("item.fargo_soul.will_power.attribute.7", "Bonus loot multiplier to x16 at max Guerrilla stacks", "游击层数达到上限时，击败敌人产生的战利品倍数提升至16倍");
        add("item.fargo_soul.will_power.attribute.8", "Damage builds up to 200% on continuous hits; drops rapidly idle", "连续攻击时造成的伤害逐渐提升至200%，不攻击时迅速降低");
        add("item.fargo_soul.will_power.tooltip.1", "\"Indomitable determination\"", "“坚不可摧的决心”");
        add("item.fargo_soul.gladiator_soul", "Gladiator Enchantment", "角斗士魔石");
        add("item.fargo_soul.gladiator_soul.attribute.1", "Summon arrow rain every 24 attacks", "持有者每24次攻击召唤一次箭雨攻击目标");
        add("item.fargo_soul.gladiator_soul.attribute.2", "Arrow rain damage to 180% if <3 nearby targets", "持有者周围的目标数少于3个时，箭雨的基础伤害提升至180%");
        add("item.fargo_soul.gladiator_soul.attribute.3", "If >=3 targets: -10% damage taken, +110% damage dealt", "持有者周围的目标数大于或等于3个时，持有者受到的伤害减少10%，造成的伤害提升至110%");
        add("item.fargo_soul.gladiator_soul.tooltip.1", "\"Are you not entertained?\"", "“你不觉得刺激吗？”");
        add("item.fargo_soul.gold_soul", "Gold Enchantment", "金魔石");
        add("item.fargo_soul.gold_soul.attribute.1", "Attacks inflict Midas", "持有者攻击会造成迈达斯减益");
        add("item.fargo_soul.gold_soul.attribute.2", "Midas-afflicted enemies drop gold ingots on death", "受迈达斯影响的目标在死亡时会掉落金锭");
        add("item.fargo_soul.gold_soul.attribute.3", "Press 'Gold Stasis' to surround yourself with golden rings for 5s; 120s CD", "按下“金身”键会将持有者包裹在两道金环中，金环持续5秒，该效果有120秒冷却");
        add("item.fargo_soul.gold_soul.attribute.4", "While in Gold Stasis, 40% damage taken is transferred as magic damage to nearby enemies", "被金环包裹时，持有者40%受到伤害将会以魔法伤害的形式转移至周围其他目标");
        add("item.fargo_soul.gold_soul.attribute.5", "Each gold ingot in inventory adds 0.1% transfer damage, up to 95%", "持有者背包中每有一个金锭会提升0.1%转移伤害，转移伤害上限为95%受到伤害");
        add("item.fargo_soul.gold_soul.attribute.7", "Immunity to Midas", "免疫迈达斯");
        add("item.fargo_soul.gold_soul.tooltip.1", "\"Money makes the world go round\"", "“有钱能使鬼推磨”");
        add("item.fargo_soul.platinum_soul", "Platinum Enchantment", "铂金魔石");
        add("item.fargo_soul.platinum_soul.attribute.1", "20% chance for enemies to drop x5 loot", "目标死亡时有20%的几率获得5倍的战利品");
        add("item.fargo_soul.platinum_soul.tooltip.1", "\"Priceless treasure\"", "“无价之宝”");
        add("item.fargo_soul.red_riding_soul", "Red Riding Enchantment", "红色骑术魔石");
        add("item.fargo_soul.red_riding_soul.attribute.1", "Damage increased to 120% against armored targets", "持有者对有护甲的目标造成伤害提升至120%");
        add("item.fargo_soul.red_riding_soul.attribute.2", "Each attack grants 1 Guerrilla stack, max 10", "持有者每次攻击时叠加1层游击，上限10层");
        add("item.fargo_soul.red_riding_soul.attribute.3", "Each stack adds +1 Armor Pen and +1% move speed", "每层游击提升持有者1点护甲穿透和1%移动速度");
        add("item.fargo_soul.red_riding_soul.attribute.4", "Dash strength increased at max stacks", "游击层数达到上限时，提升持有者冲刺强度");
        add("item.fargo_soul.red_riding_soul.attribute.5", "Stacks cleared when taking damage", "持有者受到伤害时清空游击层数");
        add("item.fargo_soul.red_riding_soul.tooltip.1", "\"Big Bad Red Riding Hood!\"", "“小红帽，大坏蛋！”");
        add("item.fargo_soul.valhalla_knight_soul", "Valhalla Knight Enchantment", "英灵殿骑士魔石");
        add("item.fargo_soul.valhalla_knight_soul.attribute.1", "Increased mount speed and jump height", "提升持有者骑乘坐骑的速度和跳跃高度");
        add("item.fargo_soul.valhalla_knight_soul.attribute.2", "Mount and rider gain 15 defense", "骑乘坐骑时，持有者与坐骑获得15点防御");
        add("item.fargo_soul.valhalla_knight_soul.attribute.3", "Mount gains immunity to fall damage", "使坐骑免疫坠落伤害");
        add("item.fargo_soul.valhalla_knight_soul.attribute.4", "Healing received increased to 115%", "持有者受到的治疗提升至115%");
        add("item.fargo_soul.valhalla_knight_soul.tooltip.1", "\"The call of Valhalla\"", "“瓦尔哈拉的呼唤”");
        add("tooltip.fargo_soul.cosmic_crucible", "Used for fusion. Contains massive storage (default 64 slots, stack limit 2,147,483,647)\nInsert items via the top; right-click empty-handed to take last item\nRetains contents when broken", "可用于融合，内含的空间可储存巨量物品(默认64格，单格堆叠上限2,147,483,647)\n通过投入或交互顶部放入物品，空手右键拿出最近放入的物品\n破坏后保留内容物");
        add("fargo_soul.screen.soul", "Soul Ability Control Interface", "魂石能力控制界面");
        add("fargo_soul.screen.is_empty", "You are not carrying any souls", "你没有携带任何魂石");
        add("fargo_soul.advancement.get", "Obtained", "获得");
        add("advancement.fargo_soul.root.title", "Forged like Stars", "如星辰般锻造");
        add("advancement.fargo_soul.terra_soul.title", "Master of Terra", "泰拉之主，天地共证");
        add("advancement.fargo_soul.cosmic_power.title", "The Stars Align", "群星连珠，命定此刻……");
        add("advancement.fargo_soul.blaze_soul.title", "Eternal Sunwheel", "烈焰焚天，日轮永恒……");
        add("advancement.fargo_soul.nebula_soul.title", "Nebula Ripples", "星云幻境，虚空涟漪……");
        add("advancement.fargo_soul.stardust_soul.title", "Frozen Stardust", "星尘流转，冻结时光……");
        add("advancement.fargo_soul.vortex_soul.title", "Abyssal Gravity", "深渊漩涡，引力扭曲……");
        add("advancement.fargo_soul.meteor_soul.title", "Meteor Fall", "天外陨星，毁灭降临……");
        add("advancement.fargo_soul.wizard_soul.title", "Arcane Secrets", "奥术奥秘，魔法掌控……");
        add("advancement.fargo_soul.death_power.title", "Deepening Darkness", "黑夜之暗，愈深愈沉……");
        add("advancement.fargo_soul.ancient_shadow_soul.title", "Spreading Terror", "暗影侵蚀，恐惧蔓延……");
        add("advancement.fargo_soul.crystal_assassin_soul.title", "Lethal Strike", "寒光闪烁，致命突袭……");
        add("advancement.fargo_soul.dark_artist_soul.title", "Ink and Flame", "墨色涌动，烈焰飞舞……");
        add("advancement.fargo_soul.gloomy_soul.title", "Soul Scorcher", "阴魂缭绕，烈焰灼魂……");
        add("advancement.fargo_soul.necromancer_soul.title", "Skeleton Awakening", "白骨森森，死灵复苏……");
        add("advancement.fargo_soul.ninja_soul.title", "Shadow Stealth", "暗影潜行，迅疾如风……");
        add("advancement.fargo_soul.penetrating_ninja_soul.title", "Heart Piercer", "利刃穿心，破甲无阻……");
        add("advancement.fargo_soul.earth_power.title", "Rumbling Core", "星球之核，隆隆作响……");
        add("advancement.fargo_soul.adamantite_soul.title", "Tidal Onslaught", "狂攻如潮，乱敌心神……");
        add("advancement.fargo_soul.cobalt_soul.title", "Oiled Burst", "油浸爆裂，烈焰焚身……");
        add("advancement.fargo_soul.mithril_soul.title", "Patient Thunder", "静待时机，迅击如雷……");
        add("advancement.fargo_soul.orichalcum_soul.title", "Petal Poison", "花落如雨，毒蚀百骸……");
        add("advancement.fargo_soul.palladium_soul.title", "Life Flow", "生命流转，愈战愈强……");
        add("advancement.fargo_soul.titanium_soul.title", "Indestructible Body", "金身不坏，疾行如风……");
        add("advancement.fargo_soul.forest_power.title", "Whispering Leaves", "林叶沙沙，环绕四周……");
        add("advancement.fargo_soul.ebony_wood_soul.title", "Dark Roots", "漆暗根须，纠缠腐土……");
        add("advancement.fargo_soul.palm_wood_soul.title", "Ocean Shadows", "咸风弄影，摇曳海浪……");
        add("advancement.fargo_soul.pearl_wood_soul.title", "Rainbow Strike", "虹彩闪耀，致命一击……");
        add("advancement.fargo_soul.pine_wood_soul.title", "Boreal Frost", "寒冰凝结，凛冽刺骨……");
        add("advancement.fargo_soul.rose_wood_soul.title", "Crimson Traction", "红丝牵引，沉淀余香……");
        add("advancement.fargo_soul.shadow_wood_soul.title", "Etched Gloom", "蚀刻幽暗，生命流逝……");
        add("advancement.fargo_soul.wood_soul.title", "Mother of All", "万物之母，孕育生机……");
        add("advancement.fargo_soul.life_power.title", "Pulse of Life", "温温生命，透体而过……");
        add("advancement.fargo_soul.bee_soul.title", "Golden Hum", "金羽嗡鸣，播撒芳华……");
        add("advancement.fargo_soul.beetle_soul.title", "Iron Carapace", "甲御千钧，坚韧不拔……");
        add("advancement.fargo_soul.pumpkin_soul.title", "Frost Moon Harvest", "霜月残面，收割丰饶……");
        add("advancement.fargo_soul.spider_soul.title", "Web of Fear", "结网千丝，狩猎恐惧……");
        add("advancement.fargo_soul.turtle_soul.title", "Rock Shell", "磐石厚甲，反哺生息……");
        add("advancement.fargo_soul.nature_power.title", "Verdant Wind", "葱茏之风，骤然吹起……");
        add("advancement.fargo_soul.crimson_soul.title", "Flesh Mutation", "血肉畸变，生命流转……");
        add("advancement.fargo_soul.lava_soul.title", "Core Wrath", "地心怒火，熔铸终焉……");
        add("advancement.fargo_soul.rain_cloud_soul.title", "Cleansing Rain", "骤雨倾盆，洗练尘寰……");
        add("advancement.fargo_soul.frost_soul.title", "Eternal Freeze", "凛冬将至，封冻永恒……");
        add("advancement.fargo_soul.green_soul.title", "Leaf Dance", "叶舞婆娑，辉映众生……");
        add("advancement.fargo_soul.mushroom_soul.title", "Fungal Resonance", "荧光微颤，共鸣深渊……");
        add("advancement.fargo_soul.spirit_power.title", "Bright Spirit", "瞿烁精神，振奋人心……");
        add("advancement.fargo_soul.forbidden_soul.title", "Desert Curse", "尘沙禁咒，回响荒漠……");
        add("advancement.fargo_soul.holy_soul.title", "Holy Baptism", "神圣洗礼，耀映凡尘……");
        add("advancement.fargo_soul.ancient_holy_soul.title", "Epic Praise", "史诗赞颂，铭刻荣光……");
        add("advancement.fargo_soul.teke_soul.title", "Transcendent Sense", "超凡感应，洞悉万象……");
        add("advancement.fargo_soul.ghost_soul.title", "Phantom Crossing", "幽冥虚渡，跨越生还……");
        add("advancement.fargo_soul.terra_power.title", "Trembling Earth", "磐石震动，四野颤抖……");
        add("advancement.fargo_soul.copper_soul.title", "Lightning Stream", "雷引流光，接续残躯……");
        add("advancement.fargo_soul.tin_soul.title", "Reshaped Edge", "铅华洗尽，重塑锋芒……");
        add("advancement.fargo_soul.iron_soul.title", "Forged Steel", "百炼成钢，横击长空……");
        add("advancement.fargo_soul.lead_soul.title", "Lead Pressure", "沉沦重压，禁锢生机……");
        add("advancement.fargo_soul.silver_soul.title", "Lunar Radiance", "皎月清辉，辟易妖邪……");
        add("advancement.fargo_soul.tungsten_soul.title", "Heavy Verdict", "极重之刃，裁决因果……");
        add("advancement.fargo_soul.obsidian_soul.title", "Frozen Abyss", "深渊凝固，抗衡烈焰……");
        add("advancement.fargo_soul.will_power.title", "Echoes of Will", "金铁呜咽，回荡深渊……");
        add("advancement.fargo_soul.gold_soul.title", "Ritual of Greed", "贪欲祭礼，铸就辉煌……");
        add("advancement.fargo_soul.platinum_soul.title", "White Oath", "纯白圣誓，坚不可摧……");
        add("advancement.fargo_soul.gladiator_soul.title", "Bloody Sand", "孤勇征程，血染黄沙……");
        add("advancement.fargo_soul.red_riding_soul.title", "Wild Hunter", "荒野猎影，撕裂黑夜……");
        add("advancement.fargo_soul.valhalla_knight_soul.title", "Valhalla's Watch", "英灵殿堂，永恒守望……");
        add("jei.fargo_soul.category.soul", "Cosmic Convergence", "宇宙聚合");
    }

    private void add(String key, String enDesc, String zhDesc) {
        LanguageProviderAccessor accessor = (LanguageProviderAccessor) this;
        String locale = accessor.getLocale();
        if (locale.equals("en_us")) {
            add(key, enDesc);
        } else if (locale.equals("zh_cn")) {
            add(key, zhDesc);
        }
    }

}
